markdown: redcarpet
permalink: pretty
baseurl: /annamisak.com
exclude: ['README.md', 'portfolio-piece-template.md']

name: Anna Misak Portfolio
description: I'm an Ottawa based creative visual thinker, designer and illustrator. I love exploring new design trends and add my own personality to the artist community.
